/**
 * 工具注册表 —— 由 scripts/generate-catalog.ts 自动生成，请勿手工编辑。
 * 生成时间：2026-09-24T09:36:41.545Z
 * 工具数：75
 */
import type { ToolMeta } from './types'

export const TOOLS: readonly ToolMeta[] = [
  {
    id: 'batch-replace',
    slug: 'batch-replace',
    title: '批量替换',
    description: '多组查找替换，支持正则',
    titleEn: 'Batch Replace',
    descriptionEn: 'Apply multiple find-and-replace rules at once, regex supported',
    category: 'text',
    group: 'dev',
    tags: ['text', 'replace', 'batch'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['useRegex', 'ignoreCase'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'blank-lines',
    slug: 'blank-lines',
    title: '空行处理',
    description: '删除、压缩空行',
    titleEn: 'Blank Line Handler',
    descriptionEn: 'Remove or collapse blank lines',
    category: 'text',
    group: 'dev',
    tags: ['text', 'blank', 'lines'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'bom',
    slug: 'bom',
    title: 'BOM 处理',
    description: '检测、添加、移除 BOM',
    titleEn: 'BOM Handler',
    descriptionEn: 'Detect, add or remove the byte order mark',
    category: 'text',
    group: 'dev',
    tags: ['text', 'bom', 'encoding'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'case-convert',
    slug: 'case-convert',
    title: '大小写转换',
    description: '大写、小写、首字母大写、标题化',
    titleEn: 'Case Convert',
    descriptionEn: 'Upper, lower, capitalize and title case',
    category: 'text',
    group: 'dev',
    tags: ['text', 'case', 'convert'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'charset-detect',
    slug: 'charset-detect',
    title: '编码检测',
    description: '检测文本编码',
    titleEn: 'Encoding Detector',
    descriptionEn: 'Detect the character encoding of text',
    category: 'text',
    group: 'dev',
    tags: ['text', 'charset', 'encoding'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['topN', 'preview'],
    deps: ['chardet'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'charset-lookup',
    slug: 'charset-lookup',
    title: '字符集查询',
    description: '查询字符所属字符集',
    titleEn: 'Charset Lookup',
    descriptionEn: 'Look up which character set a character belongs to',
    category: 'text',
    group: 'dev',
    tags: ['text', 'charset', 'unicode'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: [],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'cn-en-count',
    slug: 'cn-en-count',
    title: '中英文字数',
    description: '区分中文字符与英文单词分别计数',
    titleEn: 'Chinese / English Count',
    descriptionEn: 'Count Chinese characters and English words separately',
    category: 'text',
    group: 'dev',
    tags: ['text', 'count', 'chinese'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: [],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'cookie-parse',
    slug: 'cookie-parse',
    title: 'Cookie 解析',
    description: 'Cookie / Set-Cookie 串与对象互转，支持属性标志位',
    titleEn: 'Cookie Parser',
    descriptionEn: 'Convert Cookie and Set-Cookie strings to objects and back, with flag attributes',
    category: 'data-format',
    group: 'dev',
    tags: ['cookie', 'parse', 'header'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode', 'sortKeys'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'csv-to-tsv',
    slug: 'csv-to-tsv',
    title: 'CSV 转 TSV',
    description: 'CSV 与 TSV 互转',
    titleEn: 'CSV to TSV',
    descriptionEn: 'Convert between CSV and TSV',
    category: 'text',
    group: 'dev',
    tags: ['text', 'csv', 'convert'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode'],
    deps: ['papaparse'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'dedupe',
    slug: 'dedupe',
    title: '文本去重',
    description: '按行去重，保留顺序',
    titleEn: 'Remove Duplicate Lines',
    descriptionEn: 'Remove duplicate lines while preserving order',
    category: 'text',
    group: 'dev',
    tags: ['text', 'dedupe', 'lines'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['ignoreCase', 'trimLines', 'keepEmpty'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'diff-highlight',
    slug: 'diff-highlight',
    title: '文本对比高亮',
    description: '差异高亮显示',
    titleEn: 'Diff Highlighter',
    descriptionEn: 'Highlight the differences between two texts',
    category: 'text',
    group: 'dev',
    tags: ['text', 'diff', 'highlight'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T3',
    inputs: ['text', 'textB'],
    outputs: ['text'],
    options: ['mode'],
    deps: ['diff'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'duplicate-lines',
    slug: 'duplicate-lines',
    title: '重复行检测',
    description: '找出重复行并统计',
    titleEn: 'Duplicate Line Finder',
    descriptionEn: 'Find duplicate lines and count them',
    category: 'text',
    group: 'dev',
    tags: ['text', 'duplicate', 'lines'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode', 'trim', 'ignoreCase'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'emoji',
    slug: 'emoji',
    title: 'Emoji 查询',
    description: '搜索、复制 Emoji',
    titleEn: 'Emoji Picker',
    descriptionEn: 'Search and copy emoji',
    category: 'text',
    group: 'dev',
    tags: ['text', 'emoji', 'picker'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T3',
    inputs: ['text'],
    outputs: ['text'],
    options: ['category'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'escape',
    slug: 'escape',
    title: '转义反转义',
    description: 'JS、HTML、CSS、JSON、SQL 转义',
    titleEn: 'Escape / Unescape',
    descriptionEn: 'Escape and unescape for JS, HTML, CSS, JSON and SQL',
    category: 'text',
    group: 'dev',
    tags: ['text', 'escape', 'code'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['type', 'mode'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'extract-column',
    slug: 'extract-column',
    title: '列提取',
    description: '从文本提取指定列',
    titleEn: 'Extract Column',
    descriptionEn: 'Extract specific columns from delimited text',
    category: 'text',
    group: 'dev',
    tags: ['text', 'columns', 'extract'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['delimiter', 'columns', 'joiner', 'skipMissing'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'fullwidth-halfwidth',
    slug: 'fullwidth-halfwidth',
    title: '全角半角',
    description: '全角与半角字符互相转换',
    titleEn: 'Fullwidth / Halfwidth',
    descriptionEn: 'Convert between fullwidth and halfwidth characters',
    category: 'text',
    group: 'dev',
    tags: ['text', 'fullwidth', 'convert'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'html-to-markdown',
    slug: 'html-to-markdown',
    title: 'HTML 转 Markdown',
    description: '网页/HTML 转 Markdown',
    titleEn: 'HTML to Markdown',
    descriptionEn: 'Convert HTML or a web page fragment to Markdown',
    category: 'text',
    group: 'dev',
    tags: ['text', 'html', 'markdown'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: [],
    deps: ['turndown'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'indent',
    slug: 'indent',
    title: '缩进转换',
    description: 'Tab 与空格互转，增减缩进',
    titleEn: 'Indent Converter',
    descriptionEn: 'Convert between tabs and spaces, and shift indentation',
    category: 'text',
    group: 'dev',
    tags: ['text', 'indent', 'code'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode', 'width'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'invisible-chars',
    slug: 'invisible-chars',
    title: '不可见字符',
    description: '检测并高亮不可见字符',
    titleEn: 'Invisible Characters',
    descriptionEn: 'Detect and highlight invisible characters',
    category: 'text',
    group: 'dev',
    tags: ['text', 'invisible', 'clean'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode', 'keepCommon'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    title: 'JSON 格式化',
    description: '格式化、压缩、校验 JSON，支持树形查看',
    titleEn: 'JSON Formatter',
    descriptionEn: 'Format, minify and validate JSON, with a tree view',
    category: 'data-format',
    group: 'dev',
    tags: ['json', 'format', 'validate'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['indent', 'sortKeys'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'json-minify',
    slug: 'json-minify',
    title: 'JSON 压缩',
    description: '去除 JSON 中的空白与换行，压成单行以减小体积',
    titleEn: 'JSON Minify',
    descriptionEn: 'Strip whitespace and newlines from JSON into a single line',
    category: 'data-format',
    group: 'dev',
    tags: ['json', 'minify', 'compress'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['sortKeys'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'keyword-density',
    slug: 'keyword-density',
    title: '关键词密度',
    description: '计算关键词占比，SEO 参考',
    titleEn: 'Keyword Density',
    descriptionEn: 'Compute keyword share of text, for SEO reference',
    category: 'text',
    group: 'dev',
    tags: ['text', 'seo', 'keyword'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['topN'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'line-ending',
    slug: 'line-ending',
    title: '换行符转换',
    description: 'LF、CRLF、CR 互转',
    titleEn: 'Line Ending Converter',
    descriptionEn: 'Convert between LF, CRLF and CR line endings',
    category: 'text',
    group: 'dev',
    tags: ['text', 'line-ending', 'convert'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['target'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'line-numbers',
    slug: 'line-numbers',
    title: '行号添加',
    description: '每行添加行号，支持格式',
    titleEn: 'Add Line Numbers',
    descriptionEn: 'Prefix each line with a line number, with several formats',
    category: 'text',
    group: 'dev',
    tags: ['text', 'lines', 'format'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['format', 'align', 'skipEmpty'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'lorem',
    slug: 'lorem',
    title: 'Lorem 生成',
    description: '生成乱数假文，支持中英文',
    titleEn: 'Lorem Ipsum Generator',
    descriptionEn: 'Generate placeholder text (lorem ipsum) in Chinese, English or Latin',
    category: 'text',
    group: 'dev',
    tags: ['text', 'lorem', 'generator'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['language', 'unit', 'count'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'markdown-preview',
    slug: 'markdown-preview',
    title: 'Markdown 预览',
    description: '实时渲染 Markdown，支持 GFM',
    titleEn: 'Markdown Preview',
    descriptionEn: 'Render Markdown live, GFM supported',
    category: 'text',
    group: 'dev',
    tags: ['text', 'markdown', 'preview'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T3',
    inputs: ['text'],
    outputs: ['text'],
    options: ['breaks'],
    deps: ['markdown-it'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'markdown-to-html',
    slug: 'markdown-to-html',
    title: 'Markdown 转 HTML',
    description: '生成完整 HTML 文档',
    titleEn: 'Markdown to HTML',
    descriptionEn: 'Generate a complete HTML document',
    category: 'text',
    group: 'dev',
    tags: ['text', 'markdown', 'html'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode'],
    deps: ['markdown-it'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'multi-diff',
    slug: 'multi-diff',
    title: '多文件 Diff',
    description: '多个文本文件差异对比',
    titleEn: 'Multi-file Diff',
    descriptionEn: 'Compare several text files against a base file',
    category: 'text',
    group: 'dev',
    tags: ['text', 'diff', 'compare'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode'],
    deps: ['diff'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'naming-convert',
    slug: 'naming-convert',
    title: '命名转换',
    description: '驼峰、下划线、中划线、常量、帕斯卡互转',
    titleEn: 'Naming Convert',
    descriptionEn: 'Convert between camel, snake, kebab, constant and pascal case',
    category: 'text',
    group: 'dev',
    tags: ['text', 'naming', 'code'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'pinyin',
    slug: 'pinyin',
    title: '拼音转换',
    description: '汉字转拼音，支持声调、多音字',
    titleEn: 'Pinyin',
    descriptionEn: 'Convert Chinese characters to pinyin with tones and polyphone support',
    category: 'text',
    group: 'dev',
    tags: ['text', 'pinyin', 'chinese'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['tone'],
    deps: ['pinyin-pro'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'prefix-suffix',
    slug: 'prefix-suffix',
    title: '前后缀添加',
    description: '批量给每行加前后缀',
    titleEn: 'Add Prefix / Suffix',
    descriptionEn: 'Add a prefix and/or suffix to every line',
    category: 'text',
    group: 'dev',
    tags: ['text', 'lines', 'batch'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['prefix', 'suffix', 'skipEmpty'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'query-string',
    slug: 'query-string',
    title: 'Query String 解析',
    description: '查询串与对象互转，支持重复键与键名排序',
    titleEn: 'Query String',
    descriptionEn: 'Convert query strings to objects and back, with repeated keys and sorting',
    category: 'data-format',
    group: 'dev',
    tags: ['query', 'querystring', 'url'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode', 'sortKeys'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'readability',
    slug: 'readability',
    title: '可读性分析',
    description: 'Flesch、Gunning Fog 等可读性评分',
    titleEn: 'Readability',
    descriptionEn: 'Flesch, Gunning Fog and other readability scores',
    category: 'text',
    group: 'dev',
    tags: ['text', 'readability', 'analysis'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: [],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'reading-time',
    slug: 'reading-time',
    title: '阅读时间',
    description: '按字数估算阅读时长',
    titleEn: 'Reading Time',
    descriptionEn: 'Estimate reading time from word count',
    category: 'text',
    group: 'dev',
    tags: ['text', 'reading', 'estimate'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['speed'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'regex-replace',
    slug: 'regex-replace',
    title: '正则替换',
    description: '正则表达式替换，支持分组',
    titleEn: 'Regex Replace',
    descriptionEn: 'Replace using a regular expression, with capture group support',
    category: 'text',
    group: 'dev',
    tags: ['text', 'regex', 'replace'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['pattern', 'replacement', 'global', 'ignoreCase', 'multiline'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'rewrite',
    slug: 'rewrite',
    title: '文本改写',
    description: '同义改写、润色',
    titleEn: 'Text Rewriter',
    descriptionEn: 'Paraphrase and polish text',
    category: 'text',
    group: 'dev',
    tags: ['text', 'rewrite', 'ai'],
    priority: 'P2',
    feasibility: 'D',
    template: 'T2',
    inputs: ['text', 'apiBase', 'apiKey', 'model'],
    outputs: ['text'],
    options: ['style'],
    deps: [],
    worker: false,
    wasm: false,
    api: true,
  },
  {
    id: 'rich-to-text',
    slug: 'rich-to-text',
    title: '富文本转纯文本',
    description: '去除 HTML 标签保留文本',
    titleEn: 'Rich to Text',
    descriptionEn: 'Strip HTML tags and keep the text',
    category: 'text',
    group: 'dev',
    tags: ['text', 'html', 'strip'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['keepLineBreaks'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'sensitive-words',
    slug: 'sensitive-words',
    title: '敏感词检测',
    description: '本地词库匹配敏感词并高亮',
    titleEn: 'Sensitive Words',
    descriptionEn: 'Match sensitive words against a local list and highlight them',
    category: 'text',
    group: 'dev',
    tags: ['text', 'filter', 'detect'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mask'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'sentiment',
    slug: 'sentiment',
    title: '情感分析',
    description: '本地轻量情感倾向分析',
    titleEn: 'Sentiment',
    descriptionEn: 'Lightweight local sentiment analysis',
    category: 'text',
    group: 'dev',
    tags: ['text', 'sentiment', 'nlp'],
    priority: 'P2',
    feasibility: 'B',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['language'],
    deps: ['compromise'],
    worker: false,
    wasm: true,
    api: false,
  },
  {
    id: 'shuffle',
    slug: 'shuffle',
    title: '文本乱序',
    description: '按行、按词随机打乱',
    titleEn: 'Shuffle Text',
    descriptionEn: 'Randomly shuffle lines or words',
    category: 'text',
    group: 'dev',
    tags: ['text', 'shuffle', 'random'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode', 'stable'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'slug',
    slug: 'slug',
    title: 'Slug 生成',
    description: '标题转 URL 友好 slug，支持中文拼音',
    titleEn: 'Slug Generator',
    descriptionEn: 'Turn a title into a URL-friendly slug, with Chinese pinyin support',
    category: 'text',
    group: 'dev',
    tags: ['text', 'slug', 'url'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['chinese', 'separator', 'lowercase'],
    deps: ['pinyin-pro'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'sort',
    slug: 'sort',
    title: '文本排序',
    description: '按行排序，支持数字、长度、字典序',
    titleEn: 'Sort Lines',
    descriptionEn: 'Sort lines alphabetically, numerically or by length',
    category: 'text',
    group: 'dev',
    tags: ['text', 'sort', 'lines'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['sortBy', 'descending', 'ignoreCase'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'split-columns',
    slug: 'split-columns',
    title: '文本分列',
    description: '按分隔符分列，提取指定列',
    titleEn: 'Split Columns',
    descriptionEn: 'Split each line into columns by a delimiter',
    category: 'text',
    group: 'dev',
    tags: ['text', 'columns', 'split'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['delimiter', 'mode'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'stt',
    slug: 'stt',
    title: '语音转文本',
    description: '浏览器语音识别',
    titleEn: 'Speech to Text',
    descriptionEn: 'Speech recognition in the browser',
    category: 'text',
    group: 'dev',
    tags: ['text', 'stt', 'speech'],
    priority: 'P2',
    feasibility: 'C',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['language'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'summarize',
    slug: 'summarize',
    title: '文本摘要',
    description: '提取式或生成式摘要',
    titleEn: 'Text Summarizer',
    descriptionEn: 'Extractive or abstractive summarization',
    category: 'text',
    group: 'dev',
    tags: ['text', 'summary', 'ai'],
    priority: 'P2',
    feasibility: 'D',
    template: 'T2',
    inputs: ['text', 'apiBase', 'apiKey', 'model'],
    outputs: ['text'],
    options: ['mode', 'length'],
    deps: [],
    worker: false,
    wasm: false,
    api: true,
  },
  {
    id: 'symbols',
    slug: 'symbols',
    title: '特殊符号',
    description: '数学、箭头、货币等符号',
    titleEn: 'Special Symbols',
    descriptionEn: 'Math, arrow, currency and other symbols',
    category: 'text',
    group: 'dev',
    tags: ['text', 'symbol', 'picker'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T3',
    inputs: ['text'],
    outputs: ['text'],
    options: ['category'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'table-to-text',
    slug: 'table-to-text',
    title: '表格转文本',
    description: '表格数据转 Markdown、CSV、JSON',
    titleEn: 'Table to Text',
    descriptionEn: 'Convert tabular data to Markdown, CSV or JSON',
    category: 'text',
    group: 'dev',
    tags: ['text', 'table', 'convert'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['delimiter', 'format', 'header'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'tag-gen',
    slug: 'tag-gen',
    title: '标签生成',
    description: '自动提取标签',
    titleEn: 'Tag Generator',
    descriptionEn: 'Extract tags automatically',
    category: 'text',
    group: 'dev',
    tags: ['text', 'tag', 'ai'],
    priority: 'P2',
    feasibility: 'D',
    template: 'T2',
    inputs: ['text', 'apiBase', 'apiKey', 'model'],
    outputs: ['text'],
    options: ['mode', 'limit'],
    deps: [],
    worker: false,
    wasm: false,
    api: true,
  },
  {
    id: 'template',
    slug: 'template',
    title: '模板变量替换',
    description: '用变量替换模板占位符',
    titleEn: 'Template Variables',
    descriptionEn: 'Replace template placeholders with variables',
    category: 'text',
    group: 'dev',
    tags: ['text', 'template', 'variable'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['syntax', 'keepMissing'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-align',
    slug: 'text-align',
    title: '文本对齐',
    description: '左对齐、右对齐、居中、填充',
    titleEn: 'Text Align',
    descriptionEn: 'Left, right, center and justified alignment',
    category: 'text',
    group: 'dev',
    tags: ['text', 'align', 'format'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode', 'width', 'filler'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-compare',
    slug: 'text-compare',
    title: '文本比较',
    description: '相似度、编辑距离',
    titleEn: 'Text Compare',
    descriptionEn: 'Similarity and edit distance',
    category: 'text',
    group: 'dev',
    tags: ['text', 'compare', 'diff'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text', 'textB'],
    outputs: ['text'],
    options: ['mode'],
    deps: ['diff'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-diff',
    slug: 'text-diff',
    title: '文本 Diff',
    description: '两段文本差异对比，行级/字符级',
    titleEn: 'Text Diff',
    descriptionEn: 'Compare two texts and show differences at line or character level',
    category: 'text',
    group: 'dev',
    tags: ['text', 'diff', 'compare'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode'],
    deps: ['diff'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-encrypt',
    slug: 'text-encrypt',
    title: '文本加密',
    description: '文本 AES 加密解密',
    titleEn: 'Text Encryption',
    descriptionEn: 'Encrypt and decrypt text with AES',
    category: 'text',
    group: 'dev',
    tags: ['text', 'crypto', 'aes'],
    priority: 'P2',
    feasibility: 'C',
    template: 'T2',
    inputs: ['text', 'password'],
    outputs: ['text'],
    options: ['mode'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-hash',
    slug: 'text-hash',
    title: '文本哈希',
    description: '文本哈希值',
    titleEn: 'Text Hash',
    descriptionEn: 'Hash a piece of text',
    category: 'text',
    group: 'dev',
    tags: ['text', 'hash', 'crypto'],
    priority: 'P1',
    feasibility: 'C',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['algorithm', 'uppercase'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-merge',
    slug: 'text-merge',
    title: '文本合并',
    description: '三方合并，解决冲突',
    titleEn: 'Three-way Merge',
    descriptionEn: 'Three-way merge with conflict handling',
    category: 'text',
    group: 'dev',
    tags: ['text', 'merge', 'diff'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['prefer'],
    deps: ['diff'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-pad',
    slug: 'text-pad',
    title: '文本填充',
    description: '左右填充字符到指定长度',
    titleEn: 'Text Pad',
    descriptionEn: 'Pad text with a filler to a fixed length',
    category: 'text',
    group: 'dev',
    tags: ['text', 'pad', 'format'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode', 'length', 'filler'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-stats',
    slug: 'text-stats',
    title: '文本统计图',
    description: '词频、长度分布可视化',
    titleEn: 'Text Statistics Chart',
    descriptionEn: 'Visualize word frequency and length distribution',
    category: 'text',
    group: 'dev',
    tags: ['text', 'stats', 'chart'],
    priority: 'P2',
    feasibility: 'A',
    template: 'T3',
    inputs: ['text'],
    outputs: ['text'],
    options: ['metric', 'limit'],
    deps: ['echarts'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-to-qr',
    slug: 'text-to-qr',
    title: '文本转二维码',
    description: '文本生成二维码',
    titleEn: 'Text to QR Code',
    descriptionEn: 'Generate a QR code from text',
    category: 'text',
    group: 'dev',
    tags: ['text', 'qrcode', 'convert'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T3',
    inputs: ['text'],
    outputs: ['text'],
    options: ['level'],
    deps: ['qrcode'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-to-table',
    slug: 'text-to-table',
    title: '文本转表格',
    description: '分隔文本转表格',
    titleEn: 'Text to Table',
    descriptionEn: 'Turn delimited text into an aligned table',
    category: 'text',
    group: 'dev',
    tags: ['text', 'table', 'format'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['delimiter', 'style', 'header'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-truncate',
    slug: 'text-truncate',
    title: '文本截断',
    description: '按字数截断并加省略号',
    titleEn: 'Text Truncate',
    descriptionEn: 'Truncate text by length with an ellipsis',
    category: 'text',
    group: 'dev',
    tags: ['text', 'truncate', 'format'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode', 'limit', 'ellipsis'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-unwatermark',
    slug: 'text-unwatermark',
    title: '文本去水印',
    description: '移除零宽水印',
    titleEn: 'Text Watermark Remover',
    descriptionEn: 'Remove zero-width watermarks',
    category: 'text',
    group: 'dev',
    tags: ['text', 'watermark', 'clean'],
    priority: 'P2',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-watermark',
    slug: 'text-watermark',
    title: '文本水印',
    description: '零宽字符隐藏水印',
    titleEn: 'Text Watermark',
    descriptionEn: 'Hide a watermark in zero-width characters',
    category: 'text',
    group: 'dev',
    tags: ['text', 'watermark', 'steganography'],
    priority: 'P2',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text', 'watermark'],
    outputs: ['text'],
    options: ['mode'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-workbench',
    slug: 'text-workbench',
    title: '文本工作台',
    description: '多工具组合流水线',
    titleEn: 'Text Workbench',
    descriptionEn: 'Chain multiple text operations into a pipeline',
    category: 'text',
    group: 'dev',
    tags: ['text', 'pipeline', 'workbench'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T3',
    inputs: ['text'],
    outputs: ['text'],
    options: ['steps'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'text-wrap',
    slug: 'text-wrap',
    title: '文本换行',
    description: '按宽度自动换行',
    titleEn: 'Text Wrap',
    descriptionEn: 'Wrap text at a given width',
    category: 'text',
    group: 'dev',
    tags: ['text', 'wrap', 'format'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode', 'width', 'breakLong'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'title-gen',
    slug: 'title-gen',
    title: '标题生成',
    description: '根据内容生成标题',
    titleEn: 'Title Generator',
    descriptionEn: 'Generate titles from content',
    category: 'text',
    group: 'dev',
    tags: ['text', 'title', 'ai'],
    priority: 'P2',
    feasibility: 'D',
    template: 'T2',
    inputs: ['text', 'apiBase', 'apiKey', 'model'],
    outputs: ['text'],
    options: ['style', 'count'],
    deps: [],
    worker: false,
    wasm: false,
    api: true,
  },
  {
    id: 'translate',
    slug: 'translate',
    title: '翻译',
    description: '多语言翻译',
    titleEn: 'Translator',
    descriptionEn: 'Translate text between languages',
    category: 'text',
    group: 'dev',
    tags: ['text', 'translate', 'ai'],
    priority: 'P2',
    feasibility: 'D',
    template: 'T2',
    inputs: ['text', 'apiBase', 'apiKey', 'model'],
    outputs: ['text'],
    options: ['source', 'target'],
    deps: [],
    worker: false,
    wasm: false,
    api: true,
  },
  {
    id: 'tts',
    slug: 'tts',
    title: '文本转语音',
    description: '浏览器语音合成',
    titleEn: 'Text to Speech',
    descriptionEn: 'Speech synthesis in the browser',
    category: 'text',
    group: 'dev',
    tags: ['text', 'tts', 'speech'],
    priority: 'P2',
    feasibility: 'C',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['rate'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'unicode-lookup',
    slug: 'unicode-lookup',
    title: 'Unicode 查询',
    description: '查询字符 Unicode 编码、名称、分类',
    titleEn: 'Unicode Lookup',
    descriptionEn: 'Look up a character’s Unicode code point, category and block',
    category: 'text',
    group: 'dev',
    tags: ['text', 'unicode', 'charset'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: [],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'url-parser',
    slug: 'url-parser',
    title: 'URL 解析',
    description: '拆解 URL 的协议、主机、端口、路径、查询参数与锚点',
    titleEn: 'URL Parser',
    descriptionEn: 'Break a URL into protocol, host, port, path, query and fragment',
    category: 'data-format',
    group: 'dev',
    tags: ['url', 'parse', 'query'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: [],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'whitespace',
    slug: 'whitespace',
    title: '空白字符清理',
    description: '去首尾空格、多空格合并、去空行',
    titleEn: 'Whitespace Cleaner',
    descriptionEn: 'Trim lines, collapse repeated spaces and drop blank lines',
    category: 'text',
    group: 'dev',
    tags: ['text', 'whitespace', 'clean'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['trimLines', 'collapse', 'removeEmpty'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'word-count',
    slug: 'word-count',
    title: '字数统计',
    description: '统计字符、字、词、句、段、行、字节与阅读时间',
    titleEn: 'Word Count',
    descriptionEn: 'Count characters, words, sentences, paragraphs, lines, bytes and reading time',
    category: 'text',
    group: 'dev',
    tags: ['text', 'count', 'stats'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['countSpaces'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'word-frequency',
    slug: 'word-frequency',
    title: '词频统计',
    description: '统计词频并排序，支持停用词过滤',
    titleEn: 'Word Frequency',
    descriptionEn: 'Count and rank word frequency, with stop-word filtering',
    category: 'text',
    group: 'dev',
    tags: ['text', 'frequency', 'stats'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['topN', 'ignoreCase', 'useStopWords'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'zero-width',
    slug: 'zero-width',
    title: '零宽字符',
    description: '检测零宽字符、水印',
    titleEn: 'Zero-width Characters',
    descriptionEn: 'Detect zero-width characters and hidden watermarks',
    category: 'text',
    group: 'dev',
    tags: ['text', 'zero-width', 'watermark'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'zh-convert',
    slug: 'zh-convert',
    title: '简繁转换',
    description: '简体与繁体中文互转',
    titleEn: 'Chinese Convert',
    descriptionEn: 'Convert between Simplified and Traditional Chinese',
    category: 'text',
    group: 'dev',
    tags: ['text', 'chinese', 'convert'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode'],
    deps: ['opencc-js'],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'zhuyin',
    slug: 'zhuyin',
    title: '注音转换',
    description: '汉字转注音符号',
    titleEn: 'Zhuyin',
    descriptionEn: 'Convert Chinese characters to zhuyin (bopomofo) symbols',
    category: 'text',
    group: 'dev',
    tags: ['text', 'zhuyin', 'chinese'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['tone'],
    deps: ['pinyin-pro'],
    worker: false,
    wasm: false,
    api: false,
  },
]

const TOOL_MAP: ReadonlyMap<string, ToolMeta> = new Map(TOOLS.map((t) => [t.id, t]))

export function getTool(id: string): ToolMeta | undefined {
  return TOOL_MAP.get(id)
}

export function toolsOfCategory(category: string): readonly ToolMeta[] {
  return TOOLS.filter((t) => t.category === category)
}

export const TOOL_COUNT = TOOLS.length
