/**
 * 工具注册表 —— 由 scripts/generate-catalog.ts 自动生成，请勿手工编辑。
 * 生成时间：2026-09-24T05:21:54.005Z
 * 工具数：12
 */
import type { ToolMeta } from './types'

export const TOOLS: readonly ToolMeta[] = [
  {
    id: 'cn-en-count',
    slug: 'cn-en-count',
    title: '中英文字数',
    description: '区分中文字符与英文单词分别计数',
    titleEn: 'Chinese / English Count',
    descriptionEn: 'Count Chinese characters and English words separately',
    category: 'text',
    group: 'dev',
    tags: ['text', 'count', 'chinese'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: [],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'cookie-parse',
    slug: 'cookie-parse',
    title: 'Cookie 解析',
    description: 'Cookie / Set-Cookie 串与对象互转，支持属性标志位',
    titleEn: 'Cookie Parser',
    descriptionEn: 'Convert Cookie and Set-Cookie strings to objects and back, with flag attributes',
    category: 'data-format',
    group: 'dev',
    tags: ['cookie', 'parse', 'header'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode', 'sortKeys'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    title: 'JSON 格式化',
    description: '格式化、压缩、校验 JSON，支持树形查看',
    titleEn: 'JSON Formatter',
    descriptionEn: 'Format, minify and validate JSON, with a tree view',
    category: 'data-format',
    group: 'dev',
    tags: ['json', 'format', 'validate'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['indent', 'sortKeys'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'json-minify',
    slug: 'json-minify',
    title: 'JSON 压缩',
    description: '去除 JSON 中的空白与换行，压成单行以减小体积',
    titleEn: 'JSON Minify',
    descriptionEn: 'Strip whitespace and newlines from JSON into a single line',
    category: 'data-format',
    group: 'dev',
    tags: ['json', 'minify', 'compress'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['sortKeys'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'keyword-density',
    slug: 'keyword-density',
    title: '关键词密度',
    description: '计算关键词占比，SEO 参考',
    titleEn: 'Keyword Density',
    descriptionEn: 'Compute keyword share of text, for SEO reference',
    category: 'text',
    group: 'dev',
    tags: ['text', 'seo', 'keyword'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['topN'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'query-string',
    slug: 'query-string',
    title: 'Query String 解析',
    description: '查询串与对象互转，支持重复键与键名排序',
    titleEn: 'Query String',
    descriptionEn: 'Convert query strings to objects and back, with repeated keys and sorting',
    category: 'data-format',
    group: 'dev',
    tags: ['query', 'querystring', 'url'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mode', 'sortKeys'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'readability',
    slug: 'readability',
    title: '可读性分析',
    description: 'Flesch、Gunning Fog 等可读性评分',
    titleEn: 'Readability',
    descriptionEn: 'Flesch, Gunning Fog and other readability scores',
    category: 'text',
    group: 'dev',
    tags: ['text', 'readability', 'analysis'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: [],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'reading-time',
    slug: 'reading-time',
    title: '阅读时间',
    description: '按字数估算阅读时长',
    titleEn: 'Reading Time',
    descriptionEn: 'Estimate reading time from word count',
    category: 'text',
    group: 'dev',
    tags: ['text', 'reading', 'estimate'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['speed'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'sensitive-words',
    slug: 'sensitive-words',
    title: '敏感词检测',
    description: '本地词库匹配敏感词并高亮',
    titleEn: 'Sensitive Words',
    descriptionEn: 'Match sensitive words against a local list and highlight them',
    category: 'text',
    group: 'dev',
    tags: ['text', 'filter', 'detect'],
    priority: 'P1',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['mask'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'url-parser',
    slug: 'url-parser',
    title: 'URL 解析',
    description: '拆解 URL 的协议、主机、端口、路径、查询参数与锚点',
    titleEn: 'URL Parser',
    descriptionEn: 'Break a URL into protocol, host, port, path, query and fragment',
    category: 'data-format',
    group: 'dev',
    tags: ['url', 'parse', 'query'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: [],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'word-count',
    slug: 'word-count',
    title: '字数统计',
    description: '统计字符、字、词、句、段、行、字节与阅读时间',
    titleEn: 'Word Count',
    descriptionEn: 'Count characters, words, sentences, paragraphs, lines, bytes and reading time',
    category: 'text',
    group: 'dev',
    tags: ['text', 'count', 'stats'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['countSpaces'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
  {
    id: 'word-frequency',
    slug: 'word-frequency',
    title: '词频统计',
    description: '统计词频并排序，支持停用词过滤',
    titleEn: 'Word Frequency',
    descriptionEn: 'Count and rank word frequency, with stop-word filtering',
    category: 'text',
    group: 'dev',
    tags: ['text', 'frequency', 'stats'],
    priority: 'P0',
    feasibility: 'A',
    template: 'T2',
    inputs: ['text'],
    outputs: ['text'],
    options: ['topN', 'ignoreCase', 'useStopWords'],
    deps: [],
    worker: false,
    wasm: false,
    api: false,
  },
]

const TOOL_MAP: ReadonlyMap<string, ToolMeta> = new Map(TOOLS.map((t) => [t.id, t]))

export function getTool(id: string): ToolMeta | undefined {
  return TOOL_MAP.get(id)
}

export function toolsOfCategory(category: string): readonly ToolMeta[] {
  return TOOLS.filter((t) => t.category === category)
}

export const TOOL_COUNT = TOOLS.length
