import type { GitignoreOptions } from './schema'

/** 每个开关对应的 .gitignore 片段（不带前后空行） */
export const TEMPLATES: Readonly<Record<keyof GitignoreOptions, string[]>> = {
  node: [
    '# Node',
    'node_modules/',
    'npm-debug.log*',
    'yarn-debug.log*',
    'yarn-error.log*',
    'pnpm-debug.log*',
    '.npm',
    'dist/',
    '.env',
  ],
  python: [
    '# Python',
    '__pycache__/',
    '*.py[cod]',
    '.venv/',
    'venv/',
    '*.egg-info/',
    '.pytest_cache/',
    '.coverage',
  ],
  java: ['# Java', 'target/', '*.class', '*.jar', '*.war', '.idea/', 'build/'],
  go: ['# Go', 'bin/', '*.exe', '*.test', 'vendor/'],
  rust: ['# Rust', 'target/', 'Cargo.lock'],
  php: ['# PHP', 'vendor/', '.env', '*.log'],
  ruby: ['# Ruby', 'vendor/bundle/', '.bundle/', 'node_modules/', 'log/', '*.gem'],
  dotnet: ['# .NET', 'bin/', 'obj/', '*.user', '.vs/'],
  macos: ['# macOS', '.DS_Store', '.AppleDouble', '.LSOverride'],
  windows: ['# Windows', 'Thumbs.db', 'ehthumbs.db', 'Desktop.ini', '$RECYCLE.BIN/'],
  linux: ['# Linux', '*~', '.fuse_hidden*', '.Trash-*'],
  docker: ['# Docker', '.env.docker', 'docker-compose.override.yml'],
  ide: ['# IDE / Editor', '.vscode/', '.idea/', '*.swp', '*.swo', '.idea/workspace.xml'],
}

/** 开关 key → 中文标签（README 与界面一致） */
export const LABELS: Readonly<Record<keyof GitignoreOptions, string>> = {
  node: 'Node.js',
  python: 'Python',
  java: 'Java',
  go: 'Go',
  rust: 'Rust',
  php: 'PHP',
  ruby: 'Ruby',
  dotnet: '.NET',
  macos: 'macOS',
  windows: 'Windows',
  linux: 'Linux',
  docker: 'Docker',
  ide: 'IDE',
}

export function transform(input: { text: string }, options: GitignoreOptions): string {
  if (input.text === '') return ''
  if (input.text.length > 200000) throw new Error('输入超过 200,000 字符上限')

  const keys = Object.keys(TEMPLATES) as (keyof GitignoreOptions)[]
  const picked = keys.filter((k) => options[k])
  if (picked.length === 0) throw new Error('请至少勾选一个语言或环境')

  const blocks = picked.map((k) => TEMPLATES[k].join('\n'))
  return `# Generated by toolbox gitignore\n\n${blocks.join('\n\n')}\n`
}
