import type { HelmConfigOptions } from './schema'

/** 是否含 C0 控制字符（换行/回车等，用于阻止注入新指令） */
function hasControlChar(v: string): boolean {
  for (const ch of v) {
    if ((ch.codePointAt(0) ?? 0) <= 0x1f) return true
  }
  return false
}

/** Chart 名：小写字母/数字开头，仅含小写字母数字与“-”，长度 1-63 */
function validateName(raw: string): string {
  const name = raw.trim()
  if (!/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(name)) {
    throw new Error('Chart 名称只能包含小写字母、数字和“-”，且以字母或数字开头')
  }
  return name
}

/** 版本：主.次.补丁，可带 -预发布 / +构建；拒绝换行等 */
function validateVersion(raw: string): string {
  const v = raw.trim()
  if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(v)) {
    throw new Error('版本号需为语义化版本，如 0.1.0 或 1.2.3-rc.1')
  }
  return v
}

/** 描述：单行，禁止换行/控制字符；输出时由 YAML 双引号安全包裹 */
function validateDesc(raw: string): string {
  const d = raw.trim()
  if (hasControlChar(d)) throw new Error('描述不能包含换行或控制字符')
  return d
}

export function transform(input: { text: string }, options: HelmConfigOptions): string {
  if (input.text === '') return ''
  if (input.text.length > 200000) throw new Error('输入超过 200,000 字符上限')

  const name = options.chartName.trim() === '' ? 'mychart' : validateName(options.chartName)
  const version = options.version.trim() === '' ? '0.1.0' : validateVersion(options.version)
  const desc =
    options.description.trim() === ''
      ? 'A Helm chart generated by toolbox'
      : validateDesc(options.description)

  return [
    `# 目录结构（在 charts/${name}/ 下）`,
    `${name}/`,
    '├── Chart.yaml',
    '├── values.yaml',
    '├── templates/',
    '│   ├── deployment.yaml',
    '│   ├── service.yaml',
    '│   └── _helpers.tpl',
    '└── .helmignore',
    '',
    '# ---- Chart.yaml ----',
    'apiVersion: v2',
    `name: ${name}`,
    `description: ${JSON.stringify(desc)}`,
    'type: application',
    'version: ' + version,
    'appVersion: "1.0.0"',
    '',
    '# ---- values.yaml ----',
    'replicaCount: 1',
    'image:',
    '  repository: nginx',
    '  tag: "alpine"',
    'service:',
    '  type: ClusterIP',
    '  port: 80',
    'resources: {}',
  ].join('\n')
}
